eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false

server:
  port: 1111

spring:
  freemarker:
    template-loader-path: classpath:/templates/
    prefer-file-system-access: false
